### ISSUE TITLE
Crashes when starting

### ISSUE THREAD

**Issue by NdaruAjaa** [iLVOEWOCK/EssentialsXBE#1]
PocketMine-MP version: 5.1.3 [Protocol 589]
Git commit: 2278275505a7f9d768027673e699e6199575c8bc
PHP version: 8.1.19
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN

Error: Class "wock\essentialx\DepthStriderEnchantment" not found
File: plugins/EssentialsXBE/src/wock/essentialx/EssentialsX
Line: 67
Type: Error
Backtrace:
#0 pmsrc/src/plugin/PluginBase(76): wock\essentialx\EssentialsX->onLoad()
#1 pmsrc/src/plugin/PluginManager(216): pocketmine\plugin\PluginBase->__construct(object DevTools\FolderPluginLoader#40781, object pocketmine\Server#13, object pocketmine\plugin\PluginDescription#40823, string[39] /home/container/plugin_data/EssentialsX, string[37] /home/container/plugins/EssentialsXBE, object pocketmine\plugin\DiskResourceProvider#40854)
#2 pmsrc/src/plugin/PluginManager(368): pocketmine\plugin\PluginManager->internalLoadPlugin(string[37] /home/container/plugins/EssentialsXBE, object DevTools\FolderPluginLoader#40781, object pocketmine\plugin\PluginDescription#40823)
#3 pmsrc/src/Server(1015): pocketmine\plugin\PluginManager->loadPlugins(string[24] /home/container/plugins/, int 0)
#4 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#5 pmsrc/src/PocketMine(357): pocketmine\server()
#6 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by iLVOEWOCK** [comment]
i believe this is fully working for now, I HAVE to tell you though, this plugin is still under heavy constant development. and some featurers are either not working properly or are too slow or unstable for production use, i have it on my free testing DB which can turn off or loose data at any given moment. so it is not fully suitable for use. however i truly appreciate your feedback on this as it will help me make this plugin much better in the future. 

IF you run into anymore issues please open another request and i will get to it when i can.
